/*
 Generated by typeshare 1.13.3
*/

export enum Severity {
  Error = 'error',
  Hint = 'hint',
  Info = 'info',
  Warning = 'warning',
}

export interface Diagnostic {
  endCharacter: number;
  endLine: number;
  id: string;
  message: string;
  severity: Severity;
  startCharacter: number;
  startLine: number;
}

export interface Hover {
  content: string;
  endCharacter: number;
  endLine: number;
  markdown: boolean;
  startCharacter: number;
  startLine: number;
}
