name: Release

on:
  push:
    tags:
    - '*'

defaults:
  run:
    shell: bash

env:
  RUSTFLAGS: --deny warnings

jobs:
  prerelease:
    runs-on: ubuntu-latest

    outputs:
      value: ${{ steps.prerelease.outputs.value }}

    steps:
    - name: Prerelease Check
      id: prerelease
      run: |
        if [[ ${{ github.ref_name }} =~ ^[0-9]+[.][0-9]+[.][0-9]+$ ]]; then
          echo value=false >> "$GITHUB_OUTPUT"
        else
          echo value=true >> "$GITHUB_OUTPUT"
        fi

  package:
    strategy:
      matrix:
        target:
        - aarch64-apple-darwin
        - aarch64-unknown-linux-musl
        - arm-unknown-linux-musleabihf
        - armv7-unknown-linux-musleabihf
        - x86_64-apple-darwin
        - x86_64-pc-windows-msvc
        - aarch64-pc-windows-msvc
        - x86_64-unknown-linux-musl
        - x86_64-unknown-linux-gnu
        - aarch64-unknown-linux-gnu
        - arm-unknown-linux-gnueabihf
        - armv7-unknown-linux-gnueabihf
        include:
        - target: aarch64-apple-darwin
          os: macos-latest
          target_rustflags: ''
        - target: aarch64-unknown-linux-musl
          os: ubuntu-latest
          target_rustflags: '--codegen linker=aarch64-linux-gnu-gcc'
        - target: aarch64-unknown-linux-gnu
          os: ubuntu-latest
          target_rustflags: '--codegen linker=aarch64-linux-gnu-gcc'
        - target: arm-unknown-linux-musleabihf
          os: ubuntu-latest
          target_rustflags: '--codegen linker=arm-linux-gnueabihf-gcc'
        - target: arm-unknown-linux-gnueabihf
          os: ubuntu-latest
          target_rustflags: '--codegen linker=arm-linux-gnueabihf-gcc'
        - target: armv7-unknown-linux-musleabihf
          os: ubuntu-latest
          target_rustflags: '--codegen linker=arm-linux-gnueabihf-gcc'
        - target: armv7-unknown-linux-gnueabihf
          os: ubuntu-latest
          target_rustflags: '--codegen linker=arm-linux-gnueabihf-gcc'
        - target: x86_64-apple-darwin
          os: macos-latest
          target_rustflags: ''
        - target: x86_64-pc-windows-msvc
          os: windows-latest
        - target: aarch64-pc-windows-msvc
          os: windows-latest
          target_rustflags: ''
        - target: x86_64-unknown-linux-musl
          os: ubuntu-latest
          target_rustflags: ''
        - target: x86_64-unknown-linux-gnu
          os: ubuntu-latest
          target_rustflags: ''

    runs-on: ${{matrix.os}}

    needs: prerelease

    steps:
    - uses: actions/checkout@v4

    - name: Install AArch64 Toolchain
      if: ${{ matrix.target == 'aarch64-unknown-linux-musl' || matrix.target == 'aarch64-unknown-linux-gnu' }}
      run: |
        sudo apt-get update
        sudo apt-get install gcc-aarch64-linux-gnu libc6-dev-i386

    - name: Install musl tools
      if: ${{ contains(matrix.target, 'musl') }}
      run: |
        sudo apt-get update
        sudo apt-get install -y musl-tools

    - name: Install ARM Toolchain
      # Check if the target is an ARM hard-float ABI (eabihf) to install the appropriate toolchain
      if: ${{ contains(matrix.target, 'eabihf') }}
      run: |
        sudo apt-get update
        sudo apt-get install gcc-arm-linux-gnueabihf

    - name: Install AArch64 Toolchain (Windows)
      if: ${{ matrix.target == 'aarch64-pc-windows-msvc' }}
      run: |
        rustup target add aarch64-pc-windows-msvc

    - name: Configure compiler for Linux targets
      run: |
        if [[ "${{ matrix.target }}" == "x86_64-unknown-linux-musl" || "${{ matrix.target }}" == "x86_64-unknown-linux-gnu" ]]; then
          compiler="gcc"
        elif [[ "${{ matrix.target }}" == "aarch64-unknown-linux-musl" || "${{ matrix.target }}" == "aarch64-unknown-linux-gnu" ]]; then
          compiler="aarch64-linux-gnu-gcc"
        elif [[ "${{ matrix.target }}" == "arm-unknown-linux-musleabihf" || "${{ matrix.target }}" == "arm-unknown-linux-gnueabihf" || "${{ matrix.target }}" == "armv7-unknown-linux-musleabihf" || "${{ matrix.target }}" == "armv7-unknown-linux-gnueabihf" ]]; then
          compiler="arm-linux-gnueabihf-gcc"
        fi
        {
          echo "CC=$compiler"
          echo "CC_${{ matrix.target }}=$compiler"
          echo "CFLAGS=-D_FORTIFY_SOURCE=0 -O2"
        } >> "$GITHUB_ENV"

    - name: Package
      id: package
      env:
        TARGET: ${{ matrix.target }}
        REF: ${{ github.ref }}
        OS: ${{ matrix.os }}
        TARGET_RUSTFLAGS: ${{ matrix.target_rustflags }}
      run: ./bin/package
      shell: bash

    - name: Publish Archive
      uses: softprops/action-gh-release@v2.2.1
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      with:
        draft: false
        files: ${{ steps.package.outputs.archive }}
        prerelease: ${{ needs.prerelease.outputs.value }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish Changelog
      uses: softprops/action-gh-release@v2.2.1
      if: >-
        ${{
          startsWith(github.ref, 'refs/tags/')
          && matrix.target == 'x86_64-unknown-linux-musl'
        }}
      with:
        draft: false
        files: CHANGELOG.md
        prerelease: ${{ needs.prerelease.outputs.value }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  checksum:
    runs-on: ubuntu-latest

    needs:
    - package
    - prerelease

    steps:
    - name: Download Release Archives
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: >-
        gh release download
        --repo terror/just-lsp
        --pattern '*'
        --dir release
        ${{ github.ref_name }}

    - name: Create Checksums
      run: |
        cd release
        shasum -a 256 ./* > ../SHA256SUMS

    - name: Publish Checksums
      uses: softprops/action-gh-release@v2.2.1
      with:
        draft: false
        files: SHA256SUMS
        prerelease: ${{ needs.prerelease.outputs.value }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
