name: Web

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - '*'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: web-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v7

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: 1.4.1

    - name: Install dependencies
      working-directory: ./www
      run: bun install --frozen-lockfile

    - name: Format
      working-directory: ./www
      run: bun run format-check

    - name: Lint
      working-directory: ./www
      run: bun run lint

    - name: Test
      working-directory: ./www
      run: bun run test

    - name: Build
      working-directory: ./www
      run: bun run build
